# Site settings
title: "Rede Telenew"
description: "Lorem ipsum dolor sit amet"
madmimi: 238575
formkeep: 729ae68487eb
baseurl: ""
google_analytics: "UA-82067299-1"
search_console: "SYhVUg7tGuXQHt1Xc72jk4g5YtUCfC24c5rj6eiMNUo"
url: "https://redetelenew.com"

# User settings
razao_social: "Rede Telenew Eireli ME - CNPJ 15.065.705/0001-64"

header_title: Olá, somos a Rede Telenew.
header_description: A internet que você precisa!

slice_destaques_title: Planos
slice_destaques_description: Internet via rádio e agora também por fibra!

slice_price-table_title: Planos
slice_price-table_description: Internet via rádio e agora também por fibra!

slice_depoimentos_title: Depoimentos
slice_depoimentos_description: Veja o que os nossos clientes tem a dizer.

slice_newsletter_title: Lançamentos e promoções
slice_newsletter_description: Receba antes em seu e-mail nossos lançamentos e promoções.

telefone: (XX) XXXXX-XXXX
whatsapp: (XX) XXXXX-XXXX
email: contato@redetelenew.com
endereco: Rua Lorem Ipsum, XXX - XX - CEP XXXXX-XXX
face_username:  RedeTelenew

# Build settings
markdown: kramdown
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - top_title: Internet
    top_url: "#!/"
    nested:
      - sub_title: Planos
        sub_url: "/planos.html"
        sub_intro: "Planos sob medida pra você!"
  - top_title: Promoções
    top_url: "#!/"
    nested:
      - sub_title: Cupons
        sub_url: "/cupons.html"
        sub_intro: "Cupons exclusivos de descontos!"
      - sub_title: Adesão Grátis
        sub_url: "/adesao-gratis.html"
        sub_intro: "Não pague a taxa de adesão. Confira as regras."
  - top_title: Área
    top_url: "/area.html"
    top_intro: "Nossa área de cobertura."
  - top_title: Sobre Nós
    top_url: "/sobre.html"
    top_intro: "Um pouco sobre nossa empresa."
  - top_title: Blog
    top_url: "/blog.html"
    top_intro: "É disso que estamos falando."
  - top_title: Contato
    top_url: "/contato.html"
    top_intro: "Use o formulário abaixo para enviar sua mensagem."

# exclude my node related stuff
exclude: ['package.json', 'node_modules', '_site']
