# Site settings
title: "Rede Telenew"
description: "Lorem ipsum dolor sit amet"
madmimi: 238575
formkeep: 729ae68487eb
baseurl: ""
google_analytics: "UA-82067299-1"
search_console: "SYhVUg7tGuXQHt1Xc72jk4g5YtUCfC24c5rj6eiMNUo"
url: "https://redetelenew.com"

# User settings
razao_social: "Renato da S. Machado Inf. - ME - CNPJ 15.065.705/0001-64"

header_title: Olá, somos a Rede Telenew.
header_description: A internet que você precisa!

slice_destaques_title: Lorem
slice_destaques_description: Lorem ipsum dolor sit amet, consectetur adipisicing!

slice_depoimentos_title: Depoimentos
slice_depoimentos_description: Veja o que os nossos clientes tem a dizer.

slice_newsletter_title: Lançamentos e promoções
slice_newsletter_description: Receba em seu e-mail todos nossos lançamentos e promoções.

telefone: (XX) XXXXX-XXXX
whatsapp: (XX) XXXXX-XXXX
email: contato@redetelenew.com
endereco: Rua Lorem Ipsum, XXX - XX - CEP XXXXX-XXX
face_username:  RedeTelenew

# Build settings
markdown: kramdown
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - top_title: Internet
    top_url: "#!/"
    nested:
      - sub_title: Planos
        sub_url: "/produtos.html"
        sub_intro: "Nossos modelos profissionais exclusivos."
  - top_title: Tecnologia
    top_url: "#!/"
  - top_title: Sobre Nós
    top_url: "/sobre.html"
    top_intro: "Um pouco sobre nossa empresa."
  - top_title: Blog
    top_url: "/blog.html"
    top_intro: "É disso que estamos falando."
  - top_title: Contato
    top_url: "/contato.html"
    top_intro: "Use o formulário abaixo para enviar sua mensagem."

# exclude my node related stuff
exclude: ['package.json', 'node_modules', '_site']
