# Site settings
title: "Otimatech Telecom"
description: "Provedor de Internet"
madmimi: ""
formspree: ""
google_analytics: ""
search_console: ""
url: http://localhost:3000

# User settings
razao_social: "A. E. V. Wireless - CNPJ 15.065.705/0001-64"

header_title: Bem-vindo à Otimatech!
header_description: Planos para sua família usar à vontade

slice_price-table_title: Planos Residenciais
slice_price-table_description: Nossas soluções em internet via fibra para você

slice_depoimentos_title: Depoimentos
slice_depoimentos_description: Confira abaixo alguns depoimentos

slice_newsletter_title: Newsletter
slice_newsletter_description: Saiba antes o que acontece por aqui

email: contato@otimatech.com.br
endereco: Rua Lorem Ipsum, XXX - XX - CEP XXXXX-XXX
facebook_user:  "Otimatech-Telecom-203086623619098"

# Build settings
markdown: kramdown
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - top_title: Internet
    top_url: "/internet.html"
  - top_title: Área
    top_url: "/area.html"
    top_intro: "Nossa área de cobertura."
  - top_title: Sobre Nós
    top_url: "/sobre.html"
    top_intro: "Um pouco sobre nossa empresa."
  - top_title: Webmail
    top_url: "#"
  - top_title: Contato
    top_url: "/contato.html"
    top_intro: "Use o formulário abaixo para enviar sua mensagem."

# exclude my node related stuff
exclude: ['package.json', 'node_modules', '_site']
